
# check tx API service
[Server.APIServer]
# listen port
Port = 11556
# CORS config
AllowedOrigins = ["*"]
# Maximum number of requests to limit per second
MaxRequestsLimit = 100

# Gateways config. key is chainID
[Gateways]
1     = ["https://nodes.mewapi.io/rpc/eth", ""]

[ChainNames]
1     	= ["eth"]

