# modgodb database connection config
[Server.MongoDB]
# DBURLs is prefered if exists. forbids set both DBURL and DBURLs.
#DBURL = "localhost:27017,localhost:12345"
DBURLs = ["localhost:27017"]
DBName = "databasename"
UserName = "username"
Password = "password"

# check tx API service
[Server.APIServer]
# listen port
Port = 11556
# CORS config
AllowedOrigins = ["*"]
# Maximum number of requests to limit per second
MaxRequestsLimit = 100

# Gateways config. key is chainID
[Gateways]
4     = ["http://127.0.0.1:6711", "http://127.0.0.1:6722"]

